name: marioEnv
channels:
  - defaults
  - conda-forge
dependencies:
  - asttokens=2.0.5
  - backcall=0.2.0
  - blas=1.0
  - brotli=1.0.9
  - ca-certificates=2022.3.29
  - certifi=2021.10.8
  - colorama=0.4.4
  - cycler=0.11.0
  - debugpy=1.6.0
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=0.8.3
  - fonttools=4.25.0
  - freetype=2.10.4
  - icu=58.2
  - intel-openmp=2021.4.0
  - ipykernel=6.13.0
  - ipython=8.2.0
  - jedi=0.18.1
  - jpeg=9d
  - jupyter_client=7.2.2
  - jupyter_core=4.9.2
  - kiwisolver=1.3.2
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.2.0
  - libwebp=1.2.2
  - lz4-c=1.9.3
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.2
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - nest-asyncio=1.5.5
  - numpy-base=1.21.5
  - openssl=1.1.1n
  - packaging=21.3
  - parso=0.8.3
  - pickleshare=0.7.5
  - pillow=9.0.1
  - pip=21.2.2
  - prompt-toolkit=3.0.20
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pygments=2.11.2
  - pyparsing=3.0.8
  - pyqt=5.9.2
  - python=3.8.13
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pywin32=303
  - pyzmq=22.3.0
  - qt=5.9.7
  - setuptools=61.2.0
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.38.2
  - stack_data=0.2.0
  - tk=8.6.11
  - tornado=6.1
  - traitlets=5.1.1
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - wheel=0.37.1
  - wincertstore=0.2
  - xz=5.2.5
  - zeromq=4.3.4
  - zlib=1.2.12
  - zstd=1.4.9
  - pip:
    - cloudpickle==2.0.0
    - gym==0.21.0
    - gym-notices==0.0.6
    - gym-retro==0.8.0
    - importlib-metadata==4.11.3
    - numpy==1.22.3
    - pygame==2.1.2
    - pyglet==1.5.23
    - zipp==3.8.0
